# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1806561f4ff577bc77ac9aabb9bd1ee4ee49c8fa089ef53834ad760d06e8143a595800dfcd1308fc7639c063983ad7d8dbdf959d8da5d9ef6c2771697ebd440d

test:
  secret_key_base: e1e48d37c367a205f69fcd49ba94069a70f7ac980039c0121d4fbf8a45eef9bdb476bd8679808682cb6af8994e5e6e76d519b0ce88fac902c14b8f8ef84289a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
